# Generated by Django 4.2.7 on 2023-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_subscription',
            field=models.BooleanField(default=True, verbose_name='признак подписки'),
        ),
    ]
