# Generated by Django 4.2.7 on 2023-11-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_course_price_alter_payments_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='education.course'),
        ),
    ]
